import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: {
    default: "Spendify",
    template: "%s - Spendify"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`antialiased text-black`}
      >
        <ToastContainer position="bottom-right" />
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
